[project]
name = "data-migration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "pyautogui>=0.9.54",
    "rich>=14.0.0",
    "selenium>=4.32.0",
]
