import requests


def create_invoice_request(order_data: dict, cookies: dict, crsf_token: str) -> int:
    """
    Create an invoice request for a given order.

    :param order_data: Dictionary containing order details.
    :param cookie: Cookie string for authentication.
    :return: Response from the API as a dictionary.
    """
    url: str = "https://app.cargamaquina.com.br/speed/speedNfe/saida"

    data = {
        'YII_CSRF_TOKEN': f'{crsf_token}',
        'Nfe[_fonteTributacao]': '',
        'Nfe[_artigoTributacao]': '',
        'Nfe[armazenar]': '1',
        'Nfe[_origemNota]': '',
        'Nfe[identificador_unico]': '6076683c4b8b7d4265.28287785',
        'Nfe[tipo_operacao]': '1',
        'Nfe[natureza_id]': '37310453',
        'Nfe[finalidade_emissao]': '1',
        'Nfe[consumidor_final]': '0',
        'Nfe[destino_operacao]': '1',
        'Nfe[consumidor_final_presente]': '0',
        'Nfe[chave_referenciada]': '',
        'Nfe[uf_local_embarque]': '',
        'Nfe[local_embarque]': '',
        'Nfe[emitente_id]': '6676429',
        'Nfe[emitenteCNPJ]': '09.652.475/0001-37',
        'Nfe[emitenteRazaoSocial]': 'F&K Group Tecnologia em Sistemas Automotivos Ltda',
        'Nfe[emitenteNomeFantasia]': 'F&K Group',
        'Nfe[emitenteInscricaoEstadual]': '9045253241',
        'Nfe[emitenteInscricaoEstadualST]': '',
        'Nfe[emitenteInscricaoMunicipal]': '',
        'Nfe[emitenteCodigoRegimeTributario]': '3',
        'Nfe[emitenteEnderecoCEP]': '86050450',
        'Nfe[emitenteEnderecoLogradouro]': 'R JOAO WYCLIF',
        'Nfe[emitenteEnderecoNumero]': '111',
        'Nfe[emitenteEnderecoBairro]': 'GLEBA FAZENDA PALHANO',
        'Nfe[estadoCidadeEmitenteId]': '3446',
        'Nfe[cidadeEmitenteId]': '6838',
        'Nfe[emitenteTelefone]': '(43) 3032-5556',
        'Nfe[tipo_destinatario]': [
            '',
            'N',
        ],
        'Nfe[destinatario_id]': '37289422',
        'tituloBack': 'Destinatário',
        '[hidenExceto]': '0',
        'Nfe[tipo_documento_destinatario]': '0',
        'Nfe[cnpj_destinatario]': '60.347.923/0001-46',
        'Nfe[cpf_destinatario]': '',
        'Nfe[razao_social_destinatario]': 'LANX CABLES LTDA',
        'Nfe[tipo_inscricao_estadual_destinatario]': '1',
        'Nfe[inscricao_estadual_destinatario]': '91141047-84',
        'Nfe[inscricao_municipal_destinatario]': '',
        'Nfe[inscricao_suframa_destinatario]': '',
        'Nfe[email_destinatario]': '',
        'Nfe[cep_destinatario]': '86065000',
        'Nfe[logradouro_destinatario]': 'ARTHUR THOMAS',
        'Nfe[numero_destinatario]': '1795',
        'Nfe[bairro_destinatario]': 'RODOCENTRO',
        'Nfe[pais_destinatario]': '',
        'Nfe[uf_destinatario]': '3446',
        'Nfe[municipio_destinatario]': '6838',
        'Nfe[telefone_destinatario]': '433032-4292',
        'Nfe[complemento_destinatario]': '',
        'Nfe[cnpj_entrega]': '',
        'Nfe[cpf_entrega]': '',
        'Nfe[inscricao_estadual_entrega]': '',
        'Nfe[nome_entrega]': '',
        'Nfe[email_entrega]': '',
        'Nfe[cep_entrega]': '',
        'Nfe[logradouro_entrega]': '',
        'Nfe[numero_entrega]': '',
        'Nfe[bairro_entrega]': '',
        'Nfe[pais_entrega]': '',
        'Nfe[uf_entrega]': '',
        'Nfe[telefone_entrega]': '',
        'Nfe[complemento_entrega]': '',
        'Nfe[_totalNotaImportacao]': '',
        'processo': '',
        'infoItem': 'G',
        'ItensNota[0][numero_item]': '1',
        'ItensNota[0][codigo_produto]': 'CBM6V24PR01',
        'ItensNota[0][descricao]': 'CABO MANGA 6V 24 AWG UL2517 (AM/LR/MR/PR/VD/VM) 300V 105°C Ø EXT. 7,0mm ± 0.20mm CAPA PRETA',
        'ItensNota[0][unidade_comercial]': 'mt',
        'ItensNota[0][cfop]': '4660576',
        'ItensNota[0][quantidade_comercial]': '50',
        'ItensNota[0][valor_unitario_comercial]': '10',
        'ItensNota[0][valor_bruto]': '500.00',
        'ItensNota[0][codigo_ncm]': '85444900',
        'ItensNota[0][tipi_id]': '6010805',
        'ItensNota[0][cest]': '',
        'ItensNota[0][unidade_tributavel]': '',
        'ItensNota[0][quantidade_tributavel]': '',
        'ItensNota[0][valor_unitario_tributavel]': '',
        'ItensNota[0][valor_frete]': '',
        'ItensNota[0][valor_seguro]': '',
        'ItensNota[0][valor_desconto]': '',
        'ItensNota[0][valor_outras_despesas]': '',
        'ItensNota[0][pedido_compra]': '',
        'ItensNota[0][numero_item_pedido_compra]': '',
        'ItensNota[0][numero_fci]': '',
        'ItensNota[0][icms_situacao_tributaria]': '41',
        'ItensNota[0][icms_origem]': '0',
        'ItensNota[0][fcp_percentual]': '',
        'ItensNota[0][fcp_base_calculo]': '',
        'ItensNota[0][fcp_valor]': '',
        'ItensNota[0][icms_modalidade_base_calculo]': '0',
        'ItensNota[0][ipi_situacao_tributaria]': '51',
        'ItensNota[0][ipi_base_calculo]': '',
        'ItensNota[0][ipi_valor]': '0',
        'ItensNota[0][ipi_aliquota]': '',
        'ItensNota[0][ipi_codigo_enquadramento_legal]': '999',
        'ItensNota[0][icms_aliquota]': '',
        'ItensNota[0][icms_base_calculo]': '',
        'ItensNota[0][icms_valor]': '0',
        'ItensNota[0][icms_reducao_base_calculo]': '',
        'ItensNota[0][icms_percentual_diferimento]': '',
        'ItensNota[0][icms_valor_operacao]': '',
        'ItensNota[0][icms_valor_diferido]': '',
        'ItensNota[0][pis_situacao_tributaria]': '01',
        'ItensNota[0][pis_base_calculo]': '500',
        'ItensNota[0][pis_aliquota_valor]': '',
        'ItensNota[0][pis_aliquota_porcentual]': '1,65',
        'ItensNota[0][pis_valor]': '8,25',
        'ItensNota[0][pis_quantidade_vendida]': '',
        'ItensNota[0][cofins_situacao_tributaria]': '01',
        'ItensNota[0][cofins_base_calculo]': '500',
        'ItensNota[0][cofins_aliquota_valor]': '',
        'ItensNota[0][cofins_aliquota_porcentual]': '7,6',
        'ItensNota[0][cofins_valor]': '38,00',
        'ItensNota[0][cofins_quantidade_vendida]': '',
        'ItensNota[0][issqn_base_calculo]': '',
        'ItensNota[0][issqn_aliquota]': '',
        'ItensNota[0][issqn_valor]': '',
        'ItensNota[0][ii_base_calculo]': '500,00',
        'ItensNota[0][ii_aliquota]': '',
        'ItensNota[0][ii_valor]': '',
        'ItensNota[0][ii_despesas_aduaneiras]': '',
        'ItensNota[0][ii_valor_iof]': '',
        'ItensNota[0][informacoes_adicionais_item]': '',
        'ItensNota[0][_produtoId]': '',
        'ItensNota[0][_itemVendaId]': '',
        'ItensNota[0][rastros]': '',
        'ItensNota[0][documentos_importacao]': '',
        'ItensNota[0][icms_aliquota_credito_simples]': '',
        'ItensNota[0][icms_valor_credito_simples]': '',
        'ItensNota[0][icms_modalidade_base_calculo_st]': '6',
        'ItensNota[0][icms_reducao_base_calculo_st]': '',
        'ItensNota[0][icms_margem_valor_adicionado_st]': '',
        'ItensNota[0][icms_base_calculo_st]': '',
        'ItensNota[0][icms_aliquota_st]': '',
        'ItensNota[0][icms_valor_st]': '',
        'ItensNota[0][icms_base_calculo_retido_remetente]': '',
        'ItensNota[0][icms_valor_retido_remetente]': '',
        'ItensNota[0][icms_valor_desonerado]': '',
        'ItensNota[0][icms_motivo_desoneracao]': '0',
        'ItensNota[0][icms_deducao_desoneracao]': '0',
        'ItensNota[0][codigo_beneficio_fiscal]': 'PR800006',
        'ItensNota[0][reducao_aliquota_icms]': '',
        'ItensNota[0][inclui_no_total]': '1',
        'ItensNota[0][item_retorno_xml]': '',
        'ItensNota[0][icms_base_calculo_uf_destino]': '',
        'ItensNota[0][fcp_base_calculo_uf_destino]': '',
        'ItensNota[0][fcp_percentual_uf_destino]': '',
        'ItensNota[0][fcp_base_calculo_st]': '',
        'ItensNota[0][fcp_percentual_st]': '',
        'ItensNota[0][fcp_valor_st]': '',
        'ItensNota[0][icms_aliquota_interna_uf_destino]': '',
        'ItensNota[0][icms_aliquota_interestadual]': '',
        'ItensNota[0][icms_percentual_partilha]': '',
        'ItensNota[0][fcp_valor_uf_destino]': '',
        'ItensNota[0][icms_valor_uf_destino]': '',
        'ItensNota[0][icms_valor_uf_remetente]': '',
        'ItensNota[0][icms_base_calculo_retido_st]': '',
        'ItensNota[0][icms_aliquota_final]': '',
        'ItensNota[0][icms_valor_substituto]': '',
        'ItensNota[0][icms_valor_retido_st]': '',
        'ItensNota[0][icms_reducao_base_calculo_efetiva]': '',
        'ItensNota[0][icms_base_calculo_efetiva]': '',
        'ItensNota[0][icms_aliquota_efetiva]': '',
        'ItensNota[0][icms_valor_efetivo]': '',
        'ItensNota[0][total_tributo_federal]': '',
        'ItensNota[0][total_tributo_estadual]': '',
        'ItensNota[0][total_tributo_municipal]': '',
        'ItensNota[0][combustivel_codigo_anp]': '',
        'ItensNota[0][combustivel_descricao_anp]': '',
        'ItensNota[0][combustivel_sigla_uf]': '',
        'ItensNota[0][combustivel_percentual_glp]': '',
        'ItensNota[0][combustivel_percentual_biodiesel]': '',
        'ItensNota[0][combustivel_percentual_gas_natural_nacional]': '',
        'ItensNota[0][combustivel_valor_partida]': '',
        'ItensNota[0][combustivel_registro_codif]': '',
        'ItensNota[0][combustivel_percentual_gas_natural_importado]': '',
        'ItensNota[0][quantidade_tributada_combustivel]': '',
        'ItensNota[0][aliquota_ad_rem_combustivel]': '',
        'ItensNota[0][valor_icms_proprio_combustivel]': '',
        'ItensNota[0][quantidade_tributada_sujeita_retencao_combustivel]': '',
        'ItensNota[0][aliquota_ad_rem_retencao_combustivel]': '',
        'ItensNota[0][valor_icms_retencao_combustivel]': '',
        'ItensNota[0][valor_icms_operacao_combustivel]': '',
        'ItensNota[0][percentucal_diferimento_combustivel]': '',
        'ItensNota[0][valor_icms_diferido_combustivel]': '',
        'ItensNota[0][quantidade_tributada_retida_anteriormente_combustivel]': '',
        'ItensNota[0][aliquota_ad_rem_retido_anteriormente_combustivel]': '',
        'ItensNota[0][valor_imcs_retido_anteriormente_combustivel]': '',
        'ItensNota[0][icms_base_calculo_mono_retido]': '',
        'ItensNota[0][icms_aliquota_retido]': '',
        'ItensNota[0][icms_valor_mono_retido]': '',
        'ItensNota[0][codigo_remessa_xml]': '',
        'ItensNota[0][nota_remessa_id]': '',
        'Nfe[transportadora_id]': '',
        'Nfe[modalidade_frete]': '',
        'Nfe[valorFrete]': '',
        'Nfe[transportadorTipPessoa]': '0',
        'Nfe[cnpj_transportador]': '',
        'Nfe[cpf_transportador]': '',
        'Nfe[inscricao_estadual_transportador]': '',
        'Nfe[endereco_transportador]': '',
        'Nfe[uf_transportador]': '',
        'Nfe[municipio_transportador]': '',
        'Nfe[valor_desconto]': '',
        'Nfe[veiculo_placa]': '',
        'Nfe[veiculo_uf]': '',
        'Nfe[veiculo_rntc]': '',
        'Nfe[veiculo_identificacao_vagao]': '',
        'Nfe[veiculo_identificacao_balsa]': '',
        'Nfe[volume_quantidade]': '',
        'Nfe[volume_especie]': '',
        'Nfe[volume_marca]': '',
        'Nfe[volume_numero]': '',
        'Nfe[volume_peso_liquido]': '',
        'Nfe[volume_peso_bruto]': '',
        'Nfe[condicao_pagamento_id]': '6091530',
        'condicao': '30',
        'Nfe[forma_pagamento]': '15',
        'Nfe[bandeira_pagamento]': '01',
        'Nfe[total_nota]': '22903,4',
        'Nfe[_totalIpi]': '0',
        'PagamentosNota[0][numero]': '1',
        'PagamentosNota[0][vencimento]': '01/07/2025',
        'PagamentosNota[0][valor]': '22903,4',
        'PagamentosNota[0][forma]': '15',
        'PagamentosNota[0][_bandeira]': '01',
        'PagamentosNota[0][_aVista]': '1',
        'Nfe[info_adicionais]': 'Pedido de Compra: 21',
    }

    try:
        response = requests.post(url, cookies=cookies, data=data)
    except requests.RequestException as e:
        print(f"An error occurred while creating the invoice request: {e}")
        return 0